"""Build the acceptance-criteria traceability matrix (used by /ac-trace).

Reads every `### AC-NN` and `**AC-NN.n**` scenario from specs/app_spec.md, scans tests/ for
@pytest.mark.ac("AC-NN") markers and "AC-NN.n" docstring references, and writes
specs/reviews/ac-traceability.md. Standard library only. Exit code 1 when any AC has no test.
"""

import ast
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "specs" / "app_spec.md"
AC_HEADING = re.compile(r"^### (AC-\d{2}) — (.+)$", re.MULTILINE)
SCENARIO = re.compile(r"\*\*(AC-\d{2}\.\d+)\*\*")


def spec_criteria() -> tuple[dict[str, str], dict[str, list[str]]]:
    text = SPEC.read_text(encoding="utf-8")
    titles = dict(AC_HEADING.findall(text))
    scenarios: dict[str, list[str]] = defaultdict(list)
    for scenario in SCENARIO.findall(text):
        scenarios[scenario[:5]].append(scenario)
    return titles, scenarios


def _markers(node: ast.AST) -> list[str]:
    found = []
    for decorator in getattr(node, "decorator_list", []):
        if (isinstance(decorator, ast.Call) and getattr(decorator.func, "attr", None) == "ac"
                and decorator.args and isinstance(decorator.args[0], ast.Constant)):
            found.append(decorator.args[0].value)
    return found


def scan_tests() -> tuple[dict[str, set[str]], set[str]]:
    tests_by_ac: dict[str, set[str]] = defaultdict(set)
    scenario_refs: set[str] = set()
    for path in sorted((ROOT / "tests").rglob("test_*.py")):
        relative = path.relative_to(ROOT).as_posix()
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                for ac in _markers(node):
                    tests_by_ac[ac].add(f"{relative}::{node.name}")
                scenario_refs.update(re.findall(r"AC-\d{2}\.\d+", ast.get_docstring(node) or ""))
    return tests_by_ac, scenario_refs


def render(titles, scenarios, tests_by_ac, scenario_refs) -> str:
    lines = ["# AC traceability matrix", "", "Generated by `scripts/ac_trace_report.py` from `specs/app_spec.md` and `tests/`.",
             "", "| AC | Title | Tests | E2E | Scenarios covered |", "|---|---|---|---|---|"]
    for ac, title in sorted(titles.items()):
        tests = tests_by_ac.get(ac, set())
        e2e = "yes" if any(t.startswith("tests/e2e/") for t in tests) else "no"
        covered = [s for s in scenarios.get(ac, []) if s in scenario_refs]
        lines.append(f"| {ac} | {title} | {len(tests)} | {e2e} | {len(covered)}/{len(scenarios.get(ac, []))} |")
    lines += ["", "## Scenario gaps", ""]
    gaps = [s for ac in sorted(scenarios) for s in scenarios[ac] if s not in scenario_refs]
    lines += [f"- {gap}" for gap in gaps] or ["None — every scenario is referenced by at least one test docstring."]
    return "\n".join(lines) + "\n"


def main() -> int:
    titles, scenarios = spec_criteria()
    tests_by_ac, scenario_refs = scan_tests()
    out = ROOT / "specs" / "reviews" / "ac-traceability.md"
    out.write_text(render(titles, scenarios, tests_by_ac, scenario_refs), encoding="utf-8")
    sys.stdout.buffer.write(out.read_bytes())
    return 0 if all(tests_by_ac.get(ac) for ac in titles) else 1


if __name__ == "__main__":
    sys.exit(main())
